### ISSUE TITLE
⚡ Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/labplot#1]
Hi @chrismettal, We need to adjust a few things first to move forward, OK? ✨

First, we need to update the screenshot! We need to put a `screenshot.png` on the root of the folder.

I ask for these changes to standardize with the other repositories [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute, too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by Chrismettal** [comment]
Sure thing! I have moved the screenshot to the appropriate location.

The installation instruction screenshots have been kept under `/img` and there is another preview screenshot under `/labplot/screenshots/` which mirrors the folder structure required in labplot itself. I hope these locations are ok?

Let me know if there is anything else that needs to be standardized.

Thank you for the quick moving of the repo!

**Comment by luxonauta** [comment]
All seems good now! Thanks! 💜
